[build]
  command = "vite build"
  publish = "dist"

[[redirects]]
  from = "/api/trpc/*"
  to = "/.netlify/functions/trpc"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
